import { createFileRoute } from "@tanstack/react-router";
import { Clock, Smile, Sparkles, Ticket, TrendingUp } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis, Area, AreaChart } from "recharts";
import { AppShell } from "@/components/app-shell";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ticketVolume, resolutionTrend } from "@/lib/demo-data";
import { useSupport } from "@/lib/support-store";

export const Route = createFileRoute("/analytics")({ component: AnalyticsPage });
function Metric({label,value,icon:Icon}:{label:string;value:string;icon:typeof Clock}){return <Card><CardContent className="p-5"><Icon className="size-5 text-primary"/><p className="mt-4 text-sm text-muted-foreground">{label}</p><p className="font-display text-3xl font-semibold">{value}</p></CardContent></Card>}
function AnalyticsPage(){const {tickets}=useSupport();const resolved=tickets.filter(t=>t.status==="resolved"||t.status==="closed").length;const ai=tickets.filter(t=>t.aiHandled).length;const rated=tickets.filter(t=>t.firstResponseMins!==null);const avg=Math.round(rated.reduce((s,t)=>s+(t.firstResponseMins??0),0)/Math.max(1,rated.length));return <AppShell title="Analytics" description="Support performance, automation and customer experience trends."><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Total tickets" value={String(tickets.length)} icon={Ticket}/><Metric label="Resolved / closed" value={String(resolved)} icon={TrendingUp}/><Metric label="AI handled" value={`${Math.round(ai/tickets.length*100)}%`} icon={Sparkles}/><Metric label="Avg first response" value={`${avg}m`} icon={Clock}/></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Ticket volume</CardTitle></CardHeader><CardContent className="h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={ticketVolume}><CartesianGrid vertical={false} stroke="var(--border)"/><XAxis dataKey="day"/><YAxis/><Tooltip/><Bar dataKey="created" fill="var(--chart-1)"/><Bar dataKey="resolved" fill="var(--chart-2)"/><Bar dataKey="ai" fill="var(--chart-3)"/></BarChart></ResponsiveContainer></CardContent></Card><Card><CardHeader><CardTitle>Resolution trend</CardTitle></CardHeader><CardContent className="h-80"><ResponsiveContainer width="100%" height="100%"><AreaChart data={resolutionTrend}><CartesianGrid vertical={false} stroke="var(--border)"/><XAxis dataKey="week"/><YAxis/><Tooltip/><Area dataKey="hours" stroke="var(--chart-1)" fill="var(--chart-1)" fillOpacity={0.15}/></AreaChart></ResponsiveContainer></CardContent></Card></div><div className="mt-4 grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle>Customer experience</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-sm"><Smile className="size-4 text-primary"/>CSAT</span><strong>4.6 / 5</strong></div><div className="h-2 rounded-full bg-muted"><div className="h-2 w-[92%] rounded-full bg-primary"/></div><p className="text-xs text-muted-foreground">Based on 412 rated replies in the last 30 days.</p></CardContent></Card><Card><CardHeader><CardTitle>Automation impact</CardTitle></CardHeader><CardContent><div className="flex items-center justify-between"><span className="text-sm">Tickets handled by AI</span><strong>{ai} / {tickets.length}</strong></div><p className="mt-2 text-xs text-muted-foreground">Increase automation safely by improving knowledge coverage and confidence thresholds.</p></CardContent></Card></div></AppShell>}
