import { createFileRoute, Link } from "@tanstack/react-router";
import { MessageSquare, Search, Send, UserRound } from "lucide-react";
import { useMemo, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { PriorityBadge, StatusBadge } from "@/components/support-badges";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useSupport, priorityLabels, statusLabels, timeAgo } from "@/lib/support-store";
import type { TicketPriority, TicketStatus } from "@/lib/demo-data";
export const Route = createFileRoute("/inbox")({ component: InboxPage });
function InboxPage() { const { tickets, agents, getCustomer, updateTicket, addMessage } = useSupport(); const [query,setQuery]=useState(""); const [status,setStatus]=useState<"all"|TicketStatus>("all"); const [priority,setPriority]=useState<"all"|TicketPriority>("all"); const [selectedId,setSelectedId]=useState(tickets[0]?.id??""); const [draft,setDraft]=useState(""); const [internal,setInternal]=useState(false);
 const filtered=useMemo(()=>tickets.filter(t=>{const c=getCustomer(t.customerId);const text=`${t.id} ${t.subject} ${c?.name??""} ${c?.company??""}`.toLowerCase();return (!query||text.includes(query.toLowerCase()))&&(status==="all"||t.status===status)&&(priority==="all"||t.priority===priority)}),[tickets,query,status,priority,getCustomer]); const selected=tickets.find(t=>t.id===selectedId)??filtered[0]; const customer=selected?getCustomer(selected.customerId):undefined;
 const send=()=>{if(!selected||!draft.trim())return;addMessage(selected.id,{author:"agent",authorName:"Maya Okonkwo",body:draft.trim(),internal});setDraft("");if(!internal)updateTicket(selected.id,{status:"pending"})};
 return <AppShell title="Inbox" description={`${tickets.length} conversations · manage, reply and route support tickets`}><div className="grid min-h-[680px] gap-4 lg:grid-cols-[330px_minmax(0,1fr)_280px]"><Card className="overflow-hidden"><CardContent className="p-0"><div className="space-y-3 border-b p-3"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tickets..." className="pl-9"/></div><div className="grid grid-cols-2 gap-2"><select value={status} onChange={e=>setStatus(e.target.value as typeof status)} className="h-9 rounded-md border bg-background px-2 text-xs"><option value="all">All status</option>{Object.entries(statusLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value as typeof priority)} className="h-9 rounded-md border bg-background px-2 text-xs"><option value="all">All priority</option>{Object.entries(priorityLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div></div><div className="max-h-[590px] overflow-y-auto">{filtered.map(t=>{const c=getCustomer(t.customerId);return <button key={t.id} onClick={()=>setSelectedId(t.id)} className={`w-full border-b p-3 text-left hover:bg-accent/50 ${selected?.id===t.id?"bg-accent":""}`}><div className="flex items-start gap-2"><Avatar className="size-8"><AvatarFallback className="text-xs">{c?.initials}</AvatarFallback></Avatar><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><span className="text-xs font-semibold">{t.id}</span><span className="text-[11px] text-muted-foreground">{timeAgo(t.updatedAt)}</span></div><p className="truncate text-sm font-medium">{t.subject}</p><p className="truncate text-xs text-muted-foreground">{c?.name} · {c?.company}</p><div className="mt-2 flex gap-1"><StatusBadge status={t.status}/><PriorityBadge priority={t.priority}/></div></div></div></button>})}{!filtered.length&&<p className="p-6 text-center text-sm text-muted-foreground">No tickets match your filters.</p>}</div></CardContent></Card>
 <Card className="flex min-h-[680px] flex-col overflow-hidden">{selected?<><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><p className="text-xs text-muted-foreground">{selected.id}</p><h2 className="font-display text-lg font-semibold">{selected.subject}</h2></div><div className="flex gap-2"><select value={selected.status} onChange={e=>updateTicket(selected.id,{status:e.target.value as TicketStatus})} className="h-9 rounded-md border bg-background px-2 text-xs">{Object.entries(statusLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select value={selected.priority} onChange={e=>updateTicket(selected.id,{priority:e.target.value as TicketPriority})} className="h-9 rounded-md border bg-background px-2 text-xs">{Object.entries(priorityLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div></div><div className="flex-1 space-y-4 overflow-y-auto p-4">{selected.messages.map(m=><div key={m.id} className={`flex gap-3 ${m.internal?"rounded-lg border border-dashed p-3":""}`}><Avatar className="size-8 shrink-0"><AvatarFallback>{m.author==="customer"?customer?.initials:"AI"}</AvatarFallback></Avatar><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2 text-xs"><span className="font-semibold">{m.authorName}</span>{m.internal&&<span className="text-primary">Internal note</span>}<span className="text-muted-foreground">{timeAgo(m.at)}</span></div><p className="mt-1 whitespace-pre-wrap text-sm leading-6">{m.body}</p></div></div>)}</div><div className="border-t p-3"><div className="mb-2 flex gap-2"><Button size="sm" variant={internal?"default":"outline"} onClick={()=>setInternal(!internal)}>{internal?"Internal note":"Reply to customer"}</Button><Button size="sm" variant="outline" onClick={()=>setDraft(`Hi ${customer?.name??"there"},\n\nThanks for reaching out. I’ve reviewed your request and will help get this resolved.`)}>Use AI draft</Button></div><div className="flex gap-2"><Input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder={internal?"Add an internal note...":"Write a reply..."}/><Button onClick={send} disabled={!draft.trim()}><Send className="size-4"/>Send</Button></div></div></>:<div className="flex flex-1 items-center justify-center text-muted-foreground"><MessageSquare className="mr-2 size-5"/>Select a ticket</div>}</Card>
 <Card className="h-fit"><CardContent className="p-4">{customer&&<div className="space-y-5"><div className="flex items-center gap-3"><Avatar className="size-12"><AvatarFallback>{customer.initials}</AvatarFallback></Avatar><div><h3 className="font-semibold">{customer.name}</h3><p className="text-xs text-muted-foreground">{customer.company}</p></div></div><div className="space-y-2 text-sm"><p><span className="text-muted-foreground">Email:</span> {customer.email}</p><p><span className="text-muted-foreground">Plan:</span> {customer.plan}</p><p><span className="text-muted-foreground">Location:</span> {customer.location}</p><p><span className="text-muted-foreground">CSAT:</span> {customer.csat}/5</p></div><div><label className="text-xs font-semibold">Assignee</label><select value={selected?.assigneeId??""} onChange={e=>selected&&updateTicket(selected.id,{assigneeId:e.target.value||null})} className="mt-2 h-9 w-full rounded-md border bg-background px-2 text-sm"><option value="">Unassigned</option>{agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div><div><label className="text-xs font-semibold">Tags</label><div className="mt-2 flex flex-wrap gap-1">{selected?.tags.map(tag=><span key={tag} className="rounded bg-muted px-2 py-1 text-xs">{tag}</span>)}</div></div><Button variant="outline" className="w-full" asChild><Link to="/customers"><UserRound className="size-4"/>View customer profiles</Link></Button></div>}</CardContent></Card></div></AppShell> }
